SWIDEA_SITE/apps/devTools/urls.py
from django.urls import path
from .views import *

app_name = 'devTools'

urlpatterns = [
    path('list/', list, name='list'),
    path('create/', create, name='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
    ] 

 

SWIDEA_SITE/apps/posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
  path('', main, name='main'),
  path('create/', create, name='create'),
  path('detail/<int:pk>/', detail, name='detail'),
  path('delete/<int:pk>/', delete, name='delete'),
  path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls')),
    path('dev/', include('apps.devTools.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/apps/devTools/models.py
from django.db import models

# Create your models here.
class DevTool(models.Model):
    name = models.CharField(max_length=24)
    kind = models.CharField(max_length=24)
    content = models.CharField(max_length=100)
    

SWIDEA_SITE/apps/posts/models.py
from django.db import models
from apps.devTools.models import DevTool


# Create your models here.
class Post(models.Model):
    title = models.CharField('제목', max_length=24)
    content = models.CharField('내용', max_length=24)
    interest = models.IntegerField('관심도', default=0)
    photo = models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')

    devtool = models.ForeignKey(DevTool, on_delete=models.SET_NULL, verbose_name='예상 개발툴', null=True, blank=True)

    # 생성 시각, 수정 시각
    created_date = models.DateTimeField('작성일', auto_created=True, auto_now_add=True)
    updated_date = models.DateTimeField('수정일', auto_created=True, auto_now=True)

    SORT_CHOICE = [
        ('star', '찜하기순'),
        ('name', '이름순'),
        ('register', '등록순'),
        ('new', '최신순'),
    ]

SWIDEA_SITE/apps/devTools/forms.py
from django import forms
from .models import DevTool

class DevToolForm(forms.ModelForm):
  class Meta():
    model = DevTool
    fields = ('__all__')

SWIDEA_SITE/apps/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
  class Meta():
    model = Post
    fields = ('__all__')

SWIDEA_SITE/apps/devTools/views.py
from django.shortcuts import render, redirect
from .models import DevTool
from .forms import DevToolForm
from apps.posts.models import Post

# Create your views here.

def create(request):
    if request.method == "GET":
        form = DevToolForm()
        ctx = {'form': form}
        return render(request, 'devTools/create.html', ctx)
    form = DevToolForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
    return redirect("posts:main")

def list(request):
    devTools = DevTool.objects.all()
    ctx = {'devTools': devTools}
    return render(request, 'devTools/list.html', ctx)

def delete(request, pk):
    DevTool.objects.get(id=pk).delete()
    return redirect('devTools:list')

def update(request,pk):
    tool = DevTool.objects.get(id=pk)
    if request.method == 'GET':
        form = DevToolForm(instance=tool)
        ctx = {'form' : form, 'pk':pk}
        return render(request, 'devTools/update.html', ctx)
    
    form = DevToolForm(request.POST, instance=tool)
    if form.is_valid():
        form.save()
        return redirect('devTools:list')
    ctx = {'form': form, 'pk': pk}
    return render(request, 'devTools/update.html', ctx)

def detail(request, pk):
    devTool = DevTool.objects.get(id=pk)  # 여기서 devTool 객체를 가져옵니다.
    posts = Post.objects.filter(devtool_id=devTool.id)  # DevTool 객체의 ID로 필터링합니다.
    ctx = {'devTool': devTool, 'posts': posts}
    return render(request, 'devTools/detail.html', ctx)

SWIDEA_SITE/apps/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm

# Create your views here.
def main(request, sort_by=None):
    sort_key = request.GET.get('sort', 'new')  # 기본 정렬 기준을 'new'로 설정합니다.
    
    if sort_key == 'star':
        posts = Post.objects.order_by('-interest')
    elif sort_key == 'name':
        posts = Post.objects.order_by('title')
    elif sort_key == 'register':
        posts = Post.objects.order_by('created_date')
    elif sort_key == 'new':
        posts = Post.objects.order_by('-created_date')
    else:
        posts = Post.objects.all()

    sort_choices = [
        ('star', '찜하기순'),
        ('name', '이름순'),
        ('register', '등록순'),
        ('new', '최신순'),
    ]

    ctx = {'posts': posts, 'sort_choices': sort_choices, 'current_sort': sort_key}

    return render(request, 'posts/list.html', ctx )

def create(request):
    if request.method == "GET":
        form = PostForm()
        ctx = {'form': form}
        return render(request, 'posts/create.html', ctx)
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
    return redirect("posts:main")

def delete(request, pk):
    Post.objects.get(id=pk).delete()
    return redirect('posts:main')

def update(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == "GET":
        form = PostForm(instance=post)
        ctx = {'form':form, 'pk':pk}
        return render(request, 'posts/update.html', ctx)
    form = PostForm(request.POST, request.FILES, instance=post)
    if form.is_valid():
        form.save()
    return redirect('posts:detail', pk)

def detail(request, pk):
    post = Post.objects.get(id=pk)
    like_posts = request.session.get('liked_posts', [])
    ctx = {'post': post, 'like_posts': pk in like_posts }
    return render(request, 'posts/detail.html', ctx)


def toggle_like(request, pk):
    post = Post.objects.get(id=pk)
    like_posts = request.session.get('liked_posts', [])

    if pk in like_posts:
        like_posts.remove(pk)
        liked = False
    else:
        like_posts.append(pk)
        liked = True

    request.session['liked_posts'] = like_posts
    messages.success(request, '게시물을 찜했습니다.' if liked else '찜한 게시물을 취소했습니다.')

    return redirect('posts:detail', pk=pk)

SWIDEA_SITE/templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'posts/css/style.css'%}">  
    {%block head%}


    {% endblock %}
</head>
<body>
    <main>
        <a href="/" id='logo' style='text-decoration: none; color: black;'><h1>idea site</h1></a>
        <div>    
        <a href="{% url 'posts:create' %}" class = 'btn btn-secondary mx-2'>아이디어 등록</a>
        <a href="{% url 'posts:create' %}" class = 'btn btn-secondary mx-2'>아이디어 관리</a>
        <a href="{% url 'devTools:create' %}" class = 'btn btn-secondary mx-2'>개발툴 등록</a>
        <a href="{% url 'devTools:list' %}" class = 'btn btn-secondary mx-2'>개발툴 관리</a>   
        </div>
        <hr>
        {%block content%}
        
        
        {%endblock%}
    </main>
   <footer>
   </footer>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
</body>
</html>

SWIDEA_SITE/templates/devTools/create.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>개발툴 등록</title>
{%endblock%}

{%block content%}
    <form
        action="{% url 'devTools:create' %}"
        method="post"
        enctype="multipart/form-data"
    >
        {%csrf_token%} {{form.as_p}}
        <button class="btn btn-success">등록하기</button>
    </form>
    </div>
{%endblock%}

SWIDEA_SITE/templates/devTools/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 style="color: green; font-size: 40px">{{ devTool.name }}</h1>
    <h2 class="my-3">{{ devTool.name }}</h2>
    <p>{{ devTool.kind }}</p>
    <p>{{ devTool.content }}</p>
    <hr />

    {% if posts %}
        <ul>
            {% for post in posts %}
                <li><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No related posts found.</p>
    {% endif %}

    <form action="{% url 'devTools:delete' devTool.pk %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'devTools:update' devTool.pk %}" class="btn btn-primary">수정하기</a>
        <button type="submit" class="btn btn-danger">삭제하기</button>
    </form>
{% endblock %}

SWIDEA_SITE/templates/devTools/list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>개발툴 관리</title>
{%endblock%}
<h2>hello</h2>
{% block content %}
<div class="post-list">
    {% for devTool in devTools %}
        <div>
            <a href="{% url 'devTools:detail' devTool.pk%}" class="title">
                <h2>{{ devTool.name }}</h2>
            </a>
            <p>{{ devTool.kind }}</p>
            <p>{{ devTool.content }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}    

SWIDEA_SITE/templates/devTools/update.html
{% extends 'base.html' %}
{%block head %}
  <title>개발툴 관리</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'devTools:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
  <hr>
  <form
    action="{% url 'devTools:delete' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%}
    <button class="btn btn-danger">삭제</button>
  </form>
{%endblock%}

SWIDEA_SITE/templates/posts/create.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>post_create</title>
{% endblock %}

{%block content%}
  <form
    action="{% url 'posts:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </form>
{%endblock%}

SWIDEA_SITE/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1 style="color: green; font-size: 40px">{{post.title}}</h1>
    {% if post.photo.url != null and post.photo.url != '' %}
        <img src="{{post.photo.url}}" alt="아이디어 사진" />
    {% else %}
        <img src="{% static 'posts/image/no_img.png' %}" alt="대체 텍스트" />
    {% endif %}
        <h2 class="my-3">{{post.title}}</h2>
        <h2 class="my-3">{{post.content}}</h2>
        <p>작성일: {{post.created_date}}</p>
        <p>수정일: {{post.updated_date}}</p>
        <a href="?sort={{ key }}" class="{% if key == current_sort %}active{% endif %}">개발툴: {{devTool.name}}</a>
        


    <form action="{% url 'posts:detail' post.pk %}" method="POST">
        {% csrf_token %}
        {% if liked %}
            <button type="submit" class="btn btn-danger">찜 취소하기</button>
        {% else %}
            <button type="submit" class="btn btn-primary">찜하기</button>
        {% endif %}
    </form>

    <hr />
    <form action="{% url 'posts:delete' post.pk %}" method="POST">
        {%csrf_token%}
        <a href="{% url 'posts:update' post.pk %}" class="btn btn-primary">수정하기</a>
        <button type="submit" class="btn btn-danger">삭제하기</button>
    </form>
{% endblock content %}

SWIDEA_SITE/templates/posts/list.html
{% extends 'base.html' %}
{% load static %}

{%block head%}
  <title>Idea site</title>
{%endblock%}


{%block content%}

    <div class="container">
        <h1>Post List</h1>
        <div>
        {% for key, value in sort_choices %}
            <a href="?sort={{ key }}" class="{% if key == current_sort %}active{% endif %}">{{ value }}</a>
        {% endfor %}
    </div>
        <div class="post-list">
            {% for post in posts %}
                <div class="post">
                    {% if post.photo.url != null and post.photo.url != '' %}
                        <img src="{{post.photo.url}}" alt="사진">
                    {% else %}
                        <img src="{% static 'posts/image/no_img.png' %}" alt="대체 텍스트" />
                    {% endif %}
                    <a href="{% url 'posts:detail' post.pk%}" class="title">
                        <h2>{{ post.title }}</h2>
                    </a>
                    <p>{{ post.content }}</p>
                    <p>{{ post.interest }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{%endblock%}

SWIDEA_SITE/templates/posts/update.html
{% extends 'base.html' %}

{%block head %}
  <title>post_detail</title>
{%endblock%}

{%block content%}
  <form
    action="{% url 'posts:update' pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
{%endblock%}